# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'favoriteWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FavoriteWindow(object):
    def setupUi(self, FavoriteWindow):
        FavoriteWindow.setObjectName("FavoriteWindow")
        FavoriteWindow.setWindowModality(QtCore.Qt.NonModal)
        FavoriteWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FavoriteWindow.sizePolicy().hasHeightForWidth())
        FavoriteWindow.setSizePolicy(sizePolicy)
        FavoriteWindow.setMaximumSize(QtCore.QSize(855, 661))
        font = QtGui.QFont()
        font.setPointSize(15)
        FavoriteWindow.setFont(font)
        FavoriteWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        FavoriteWindow.setProperty("dockNestingEnabled", False)
        FavoriteWindow.setProperty("unifiedTitleAndToolBarOnMac", False)
        self.gridLayout = QtWidgets.QGridLayout(FavoriteWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(0, -1, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backBtn = QtWidgets.QPushButton(FavoriteWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backBtn.sizePolicy().hasHeightForWidth())
        self.backBtn.setSizePolicy(sizePolicy)
        self.backBtn.setMinimumSize(QtCore.QSize(64, 64))
        self.backBtn.setMaximumSize(QtCore.QSize(64, 64))
        self.backBtn.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.backBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BlueBackIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.backBtn.setIcon(icon)
        self.backBtn.setIconSize(QtCore.QSize(64, 64))
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_2.addWidget(self.backBtn)
        spacerItem = QtWidgets.QSpacerItem(214, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.homeBtn = QtWidgets.QPushButton(FavoriteWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeBtn.sizePolicy().hasHeightForWidth())
        self.homeBtn.setSizePolicy(sizePolicy)
        self.homeBtn.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.homeBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/SSLogo_No_Background.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon1)
        self.homeBtn.setIconSize(QtCore.QSize(256, 64))
        self.homeBtn.setCheckable(False)
        self.homeBtn.setChecked(False)
        self.homeBtn.setObjectName("homeBtn")
        self.gridLayout_5.addWidget(self.homeBtn, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(260, 63, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setColumnStretch(2, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 2, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 0, 1, 1)
        self.categoryTabWidget = QtWidgets.QTabWidget(FavoriteWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.categoryTabWidget.sizePolicy().hasHeightForWidth())
        self.categoryTabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.categoryTabWidget.setFont(font)
        self.categoryTabWidget.setAcceptDrops(True)
        self.categoryTabWidget.setStyleSheet("")
        self.categoryTabWidget.setObjectName("categoryTabWidget")
        self.favoritesTab = QtWidgets.QWidget()
        self.favoritesTab.setObjectName("favoritesTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.favoritesTab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.favoritesTableView = TileView(self.favoritesTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favoritesTableView.sizePolicy().hasHeightForWidth())
        self.favoritesTableView.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.favoritesTableView.setFont(font)
        self.favoritesTableView.setStyleSheet("")
        self.favoritesTableView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.favoritesTableView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.favoritesTableView.setLineWidth(0)
        self.favoritesTableView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.favoritesTableView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.favoritesTableView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.favoritesTableView.setAutoScroll(True)
        self.favoritesTableView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.favoritesTableView.setDragEnabled(True)
        self.favoritesTableView.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.favoritesTableView.setDefaultDropAction(QtCore.Qt.ActionMask)
        self.favoritesTableView.setAlternatingRowColors(True)
        self.favoritesTableView.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.favoritesTableView.setTextElideMode(QtCore.Qt.ElideRight)
        self.favoritesTableView.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.favoritesTableView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.favoritesTableView.setShowGrid(True)
        self.favoritesTableView.setWordWrap(True)
        self.favoritesTableView.setObjectName("favoritesTableView")
        self.favoritesTableView.horizontalHeader().setVisible(False)
        self.favoritesTableView.horizontalHeader().setDefaultSectionSize(154)
        self.favoritesTableView.verticalHeader().setVisible(False)
        self.favoritesTableView.verticalHeader().setDefaultSectionSize(90)
        self.gridLayout_4.addWidget(self.favoritesTableView, 0, 0, 1, 1)
        self.categoryTabWidget.addTab(self.favoritesTab, "")
        self.gridLayout.addWidget(self.categoryTabWidget, 3, 0, 1, 3)
        self.floatingBtnWidget = QtWidgets.QWidget(FavoriteWindow)
        self.floatingBtnWidget.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.floatingBtnWidget.setObjectName("floatingBtnWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.floatingBtnWidget)
        self.horizontalLayout.setContentsMargins(0, 3, 0, 6)
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBtn = QtWidgets.QPushButton(self.floatingBtnWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addBtn.sizePolicy().hasHeightForWidth())
        self.addBtn.setSizePolicy(sizePolicy)
        self.addBtn.setMinimumSize(QtCore.QSize(48, 48))
        self.addBtn.setMaximumSize(QtCore.QSize(48, 48))
        self.addBtn.setStyleSheet("background-color: transparent; border: 0;")
        self.addBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/GreenPlusIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addBtn.setIcon(icon2)
        self.addBtn.setIconSize(QtCore.QSize(48, 48))
        self.addBtn.setObjectName("addBtn")
        self.horizontalLayout.addWidget(self.addBtn)
        self.removeBtn = QtWidgets.QPushButton(self.floatingBtnWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeBtn.sizePolicy().hasHeightForWidth())
        self.removeBtn.setSizePolicy(sizePolicy)
        self.removeBtn.setMinimumSize(QtCore.QSize(48, 48))
        self.removeBtn.setMaximumSize(QtCore.QSize(48, 48))
        self.removeBtn.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.removeBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/RedMinusIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeBtn.setIcon(icon3)
        self.removeBtn.setIconSize(QtCore.QSize(48, 48))
        self.removeBtn.setObjectName("removeBtn")
        self.horizontalLayout.addWidget(self.removeBtn)
        self.gridLayout.addWidget(self.floatingBtnWidget, 4, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.listAddBtn = QtWidgets.QPushButton(FavoriteWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listAddBtn.sizePolicy().hasHeightForWidth())
        self.listAddBtn.setSizePolicy(sizePolicy)
        self.listAddBtn.setMinimumSize(QtCore.QSize(48, 48))
        self.listAddBtn.setMaximumSize(QtCore.QSize(48, 48))
        self.listAddBtn.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listAddBtn.setStyleSheet("background-color: transparent;\n"
"border: 0;r")
        self.listAddBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/EditIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listAddBtn.setIcon(icon4)
        self.listAddBtn.setIconSize(QtCore.QSize(48, 48))
        self.listAddBtn.setObjectName("listAddBtn")
        self.horizontalLayout_3.addWidget(self.listAddBtn)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)

        self.retranslateUi(FavoriteWindow)
        self.categoryTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FavoriteWindow)

    def retranslateUi(self, FavoriteWindow):
        _translate = QtCore.QCoreApplication.translate
        FavoriteWindow.setWindowTitle(_translate("FavoriteWindow", "Smart Shop"))
        self.categoryTabWidget.setTabText(self.categoryTabWidget.indexOf(self.favoritesTab), _translate("FavoriteWindow", "Favorite\'s"))

from Widgets.tileView import TileView
import Resource_BY_rc
import style_rc
