# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setProperty("dockNestingEnabled", False)
        MainWindow.setProperty("unifiedTitleAndToolBarOnMac", False)
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 6)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(12, -1, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.reqItemsWidget = QtWidgets.QListWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.reqItemsWidget.setFont(font)
        self.reqItemsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.reqItemsWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.reqItemsWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.reqItemsWidget.setAlternatingRowColors(True)
        self.reqItemsWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.reqItemsWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.reqItemsWidget.setObjectName("reqItemsWidget")
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.reqItemsWidget.addItem(item)
        self.gridLayout_3.addWidget(self.reqItemsWidget, 2, 0, 1, 1)
        self.EditShopingListButton = QtWidgets.QPushButton(MainWindow)
        self.EditShopingListButton.setMinimumSize(QtCore.QSize(0, 53))
        self.EditShopingListButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(22)
        self.EditShopingListButton.setFont(font)
        self.EditShopingListButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/BinocularsIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.EditShopingListButton.setIcon(icon)
        self.EditShopingListButton.setIconSize(QtCore.QSize(32, 32))
        self.EditShopingListButton.setObjectName("EditShopingListButton")
        self.gridLayout_3.addWidget(self.EditShopingListButton, 0, 0, 1, 2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.PlusMinusButton = QtWidgets.QPushButton(MainWindow)
        self.PlusMinusButton.setMinimumSize(QtCore.QSize(64, 64))
        self.PlusMinusButton.setMaximumSize(QtCore.QSize(64, 64))
        self.PlusMinusButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.PlusMinusButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/RedMinusIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/GreenPlusIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PlusMinusButton.setIcon(icon1)
        self.PlusMinusButton.setIconSize(QtCore.QSize(58, 58))
        self.PlusMinusButton.setCheckable(True)
        self.PlusMinusButton.setObjectName("PlusMinusButton")
        self.verticalLayout_4.addWidget(self.PlusMinusButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.ManualAddButton = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManualAddButton.sizePolicy().hasHeightForWidth())
        self.ManualAddButton.setSizePolicy(sizePolicy)
        self.ManualAddButton.setMinimumSize(QtCore.QSize(64, 64))
        self.ManualAddButton.setMaximumSize(QtCore.QSize(64, 64))
        self.ManualAddButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.ManualAddButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/FingerIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ManualAddButton.setIcon(icon2)
        self.ManualAddButton.setIconSize(QtCore.QSize(58, 58))
        self.ManualAddButton.setObjectName("ManualAddButton")
        self.verticalLayout_4.addWidget(self.ManualAddButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.ViewInventoryButton = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ViewInventoryButton.sizePolicy().hasHeightForWidth())
        self.ViewInventoryButton.setSizePolicy(sizePolicy)
        self.ViewInventoryButton.setMinimumSize(QtCore.QSize(64, 64))
        self.ViewInventoryButton.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(22)
        self.ViewInventoryButton.setFont(font)
        self.ViewInventoryButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.ViewInventoryButton.setText("")
        self.ViewInventoryButton.setIcon(icon)
        self.ViewInventoryButton.setIconSize(QtCore.QSize(58, 58))
        self.ViewInventoryButton.setObjectName("ViewInventoryButton")
        self.verticalLayout_4.addWidget(self.ViewInventoryButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.SettingsButton = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsButton.sizePolicy().hasHeightForWidth())
        self.SettingsButton.setSizePolicy(sizePolicy)
        self.SettingsButton.setMinimumSize(QtCore.QSize(64, 64))
        self.SettingsButton.setMaximumSize(QtCore.QSize(64, 64))
        self.SettingsButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.SettingsButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/BlueSettingsIconSOLID_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsButton.setIcon(icon3)
        self.SettingsButton.setIconSize(QtCore.QSize(58, 58))
        self.SettingsButton.setObjectName("SettingsButton")
        self.verticalLayout_4.addWidget(self.SettingsButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 7, 3, 1)
        self.label_4 = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 6, 1, 1)
        self.line_2 = QtWidgets.QFrame(MainWindow)
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 3, 3, 1)
        self.recItemsWidget = QtWidgets.QTableWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.recItemsWidget.setFont(font)
        self.recItemsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recItemsWidget.setDragEnabled(True)
        self.recItemsWidget.setDragDropOverwriteMode(False)
        self.recItemsWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.recItemsWidget.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.recItemsWidget.setAlternatingRowColors(True)
        self.recItemsWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.recItemsWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.recItemsWidget.setShowGrid(False)
        self.recItemsWidget.setRowCount(12)
        self.recItemsWidget.setColumnCount(2)
        self.recItemsWidget.setObjectName("recItemsWidget")
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.recItemsWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.recItemsWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.recItemsWidget.setItem(7, 1, item)
        self.recItemsWidget.horizontalHeader().setVisible(True)
        self.recItemsWidget.horizontalHeader().setStretchLastSection(True)
        self.recItemsWidget.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.recItemsWidget, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_2.setHorizontalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(MainWindow)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 1, 0, 1, 3)
        self.homeBtn = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeBtn.sizePolicy().hasHeightForWidth())
        self.homeBtn.setSizePolicy(sizePolicy)
        self.homeBtn.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.homeBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/SSLogo_No_Background.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon4)
        self.homeBtn.setIconSize(QtCore.QSize(256, 64))
        self.homeBtn.setCheckable(False)
        self.homeBtn.setChecked(False)
        self.homeBtn.setObjectName("homeBtn")
        self.gridLayout_2.addWidget(self.homeBtn, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Shop"))
        __sortingEnabled = self.reqItemsWidget.isSortingEnabled()
        self.reqItemsWidget.setSortingEnabled(False)
        item = self.reqItemsWidget.item(0)
        item.setText(_translate("MainWindow", "Apples"))
        item = self.reqItemsWidget.item(1)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(2)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(3)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(4)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(5)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(6)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(7)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(8)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(9)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(10)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(11)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.reqItemsWidget.item(12)
        item.setText(_translate("MainWindow", "Bananas"))
        item = self.reqItemsWidget.item(13)
        item.setText(_translate("MainWindow", "Onions"))
        self.reqItemsWidget.setSortingEnabled(__sortingEnabled)
        self.EditShopingListButton.setText(_translate("MainWindow", "Shopping List"))
        self.label_4.setText(_translate("MainWindow", "Recommended Items"))
        self.label_3.setText(_translate("MainWindow", "Required Items"))
        item = self.recItemsWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Item"))
        item = self.recItemsWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Qty"))
        __sortingEnabled = self.recItemsWidget.isSortingEnabled()
        self.recItemsWidget.setSortingEnabled(False)
        item = self.recItemsWidget.item(0, 0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.recItemsWidget.item(0, 1)
        item.setText(_translate("MainWindow", "101"))
        item = self.recItemsWidget.item(1, 0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.recItemsWidget.item(1, 1)
        item.setText(_translate("MainWindow", "102"))
        item = self.recItemsWidget.item(2, 0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.recItemsWidget.item(2, 1)
        item.setText(_translate("MainWindow", "103"))
        item = self.recItemsWidget.item(3, 0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.recItemsWidget.item(3, 1)
        item.setText(_translate("MainWindow", "104"))
        item = self.recItemsWidget.item(4, 0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.recItemsWidget.item(4, 1)
        item.setText(_translate("MainWindow", "401"))
        item = self.recItemsWidget.item(5, 0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.recItemsWidget.item(5, 1)
        item.setText(_translate("MainWindow", "301"))
        item = self.recItemsWidget.item(6, 0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.recItemsWidget.item(6, 1)
        item.setText(_translate("MainWindow", "201"))
        item = self.recItemsWidget.item(7, 0)
        item.setText(_translate("MainWindow", "New Item"))
        item = self.recItemsWidget.item(7, 1)
        item.setText(_translate("MainWindow", "100"))
        self.recItemsWidget.setSortingEnabled(__sortingEnabled)

import Resource_BY_rc
import style_rc
