# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setProperty("dockNestingEnabled", False)
        MainWindow.setProperty("unifiedTitleAndToolBarOnMac", False)
        self.gridLayout = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout.setContentsMargins(0, 0, 0, 6)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(12, -1, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.checkInOutBtn = TouchButton(MainWindow)
        self.checkInOutBtn.setMinimumSize(QtCore.QSize(64, 64))
        self.checkInOutBtn.setMaximumSize(QtCore.QSize(64, 64))
        self.checkInOutBtn.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.checkInOutBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/GreenPlusIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/RedMinusIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.checkInOutBtn.setIcon(icon)
        self.checkInOutBtn.setIconSize(QtCore.QSize(58, 58))
        self.checkInOutBtn.setCheckable(True)
        self.checkInOutBtn.setObjectName("checkInOutBtn")
        self.verticalLayout_4.addWidget(self.checkInOutBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.ManualAddButton = TouchButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ManualAddButton.sizePolicy().hasHeightForWidth())
        self.ManualAddButton.setSizePolicy(sizePolicy)
        self.ManualAddButton.setMinimumSize(QtCore.QSize(64, 64))
        self.ManualAddButton.setMaximumSize(QtCore.QSize(64, 64))
        self.ManualAddButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.ManualAddButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/FingerIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ManualAddButton.setIcon(icon1)
        self.ManualAddButton.setIconSize(QtCore.QSize(58, 58))
        self.ManualAddButton.setObjectName("ManualAddButton")
        self.verticalLayout_4.addWidget(self.ManualAddButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.PurchaseHistoryButton = TouchButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PurchaseHistoryButton.sizePolicy().hasHeightForWidth())
        self.PurchaseHistoryButton.setSizePolicy(sizePolicy)
        self.PurchaseHistoryButton.setMinimumSize(QtCore.QSize(64, 64))
        self.PurchaseHistoryButton.setMaximumSize(QtCore.QSize(64, 64))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(22)
        self.PurchaseHistoryButton.setFont(font)
        self.PurchaseHistoryButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.PurchaseHistoryButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Icons/ShoppingCart2_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PurchaseHistoryButton.setIcon(icon2)
        self.PurchaseHistoryButton.setIconSize(QtCore.QSize(58, 58))
        self.PurchaseHistoryButton.setObjectName("PurchaseHistoryButton")
        self.verticalLayout_4.addWidget(self.PurchaseHistoryButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.SettingsButton = TouchButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SettingsButton.sizePolicy().hasHeightForWidth())
        self.SettingsButton.setSizePolicy(sizePolicy)
        self.SettingsButton.setMinimumSize(QtCore.QSize(64, 64))
        self.SettingsButton.setMaximumSize(QtCore.QSize(64, 64))
        self.SettingsButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SettingsButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.SettingsButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/Icons/BlueSettingsIconSOLID_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsButton.setIcon(icon3)
        self.SettingsButton.setIconSize(QtCore.QSize(58, 58))
        self.SettingsButton.setObjectName("SettingsButton")
        self.verticalLayout_4.addWidget(self.SettingsButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.verticalLayout_4, 0, 7, 5, 1)
        self.label_4 = QtWidgets.QLabel(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(MainWindow)
        self.line_2.setLineWidth(1)
        self.line_2.setMidLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 3, 5, 1)
        spacerItem5 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 6, 1, 1)
        self.floatingPB1 = QtWidgets.QPushButton(MainWindow)
        self.floatingPB1.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.floatingPB1.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icons/Icons/RedMinusIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.floatingPB1.setIcon(icon4)
        self.floatingPB1.setIconSize(QtCore.QSize(58, 58))
        self.floatingPB1.setObjectName("floatingPB1")
        self.gridLayout_3.addWidget(self.floatingPB1, 2, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 2, 1, 1)
        self.printShoppingListButton = TouchButton(MainWindow)
        self.printShoppingListButton.setMinimumSize(QtCore.QSize(0, 53))
        self.printShoppingListButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(22)
        self.printShoppingListButton.setFont(font)
        self.printShoppingListButton.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icons/Icons/PrintIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printShoppingListButton.setIcon(icon5)
        self.printShoppingListButton.setIconSize(QtCore.QSize(32, 32))
        self.printShoppingListButton.setCheckable(False)
        self.printShoppingListButton.setObjectName("printShoppingListButton")
        self.gridLayout_3.addWidget(self.printShoppingListButton, 0, 0, 1, 2)
        self.floatingPB2 = QtWidgets.QPushButton(MainWindow)
        self.floatingPB2.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.floatingPB2.setText("")
        self.floatingPB2.setIcon(icon4)
        self.floatingPB2.setIconSize(QtCore.QSize(58, 58))
        self.floatingPB2.setObjectName("floatingPB2")
        self.gridLayout_3.addWidget(self.floatingPB2, 3, 0, 1, 1)
        self.recItemsWidget = QtWidgets.QTableView(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.recItemsWidget.setFont(font)
        self.recItemsWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.recItemsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.recItemsWidget.setDragEnabled(True)
        self.recItemsWidget.setDragDropOverwriteMode(False)
        self.recItemsWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.recItemsWidget.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.recItemsWidget.setAlternatingRowColors(True)
        self.recItemsWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.recItemsWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.recItemsWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.recItemsWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.recItemsWidget.setShowGrid(False)
        self.recItemsWidget.setSortingEnabled(True)
        self.recItemsWidget.setObjectName("recItemsWidget")
        self.recItemsWidget.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.recItemsWidget, 4, 1, 1, 1)
        self.reqItemsWidget = QtWidgets.QTableView(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(19)
        self.reqItemsWidget.setFont(font)
        self.reqItemsWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.reqItemsWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.reqItemsWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.reqItemsWidget.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.reqItemsWidget.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.reqItemsWidget.setAlternatingRowColors(True)
        self.reqItemsWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.reqItemsWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.reqItemsWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.reqItemsWidget.setSortingEnabled(True)
        self.reqItemsWidget.setObjectName("reqItemsWidget")
        self.reqItemsWidget.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.reqItemsWidget, 4, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_2.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_2.setHorizontalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(MainWindow)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 1, 0, 1, 3)
        self.homeBtn = QtWidgets.QPushButton(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeBtn.sizePolicy().hasHeightForWidth())
        self.homeBtn.setSizePolicy(sizePolicy)
        self.homeBtn.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.homeBtn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Icons/Icons/SSLogo_No_Background.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeBtn.setIcon(icon6)
        self.homeBtn.setIconSize(QtCore.QSize(256, 64))
        self.homeBtn.setCheckable(False)
        self.homeBtn.setChecked(False)
        self.homeBtn.setObjectName("homeBtn")
        self.gridLayout_2.addWidget(self.homeBtn, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Shop"))
        self.label_3.setText(_translate("MainWindow", "Required Items"))
        self.label_4.setText(_translate("MainWindow", "Recommended Items"))
        self.printShoppingListButton.setText(_translate("MainWindow", "Shopping List"))

from Widgets.touchButton import TouchButton
import Resource_BY_rc
import style_rc
