# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewItemDetails.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewItemDetails(object):
    def setupUi(self, NewItemDetails):
        NewItemDetails.setObjectName("NewItemDetails")
        NewItemDetails.resize(555, 406)
        font = QtGui.QFont()
        font.setPointSize(19)
        NewItemDetails.setFont(font)
        NewItemDetails.setStyleSheet("QDialog\n"
"{\n"
"    border: 1px solid #76797C;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(NewItemDetails)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setVerticalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_1.setSpacing(15)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem)
        self.accept_button = TouchButton(NewItemDetails)
        self.accept_button.setMinimumSize(QtCore.QSize(48, 48))
        self.accept_button.setMaximumSize(QtCore.QSize(48, 48))
        self.accept_button.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.accept_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/GreenCheckIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accept_button.setIcon(icon)
        self.accept_button.setIconSize(QtCore.QSize(48, 48))
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout_1.addWidget(self.accept_button)
        self.cancel_button = TouchButton(NewItemDetails)
        self.cancel_button.setMinimumSize(QtCore.QSize(48, 48))
        self.cancel_button.setMaximumSize(QtCore.QSize(48, 48))
        self.cancel_button.setStyleSheet("background-color: transparent;\n"
"border: 0;")
        self.cancel_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/RedCancelIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_button.setIcon(icon1)
        self.cancel_button.setIconSize(QtCore.QSize(48, 48))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_1.addWidget(self.cancel_button)
        self.gridLayout.addLayout(self.horizontalLayout_1, 2, 1, 1, 3)
        self.groupBox_optional = QtWidgets.QGroupBox(NewItemDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_optional.sizePolicy().hasHeightForWidth())
        self.groupBox_optional.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.groupBox_optional.setFont(font)
        self.groupBox_optional.setStyleSheet("QGroupBox\n"
"{\n"
"    margin-top: 25px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    padding-top: 0px;\n"
"    margin-top: 0px;\n"
"    margin-bottom: 5px;\n"
"    /*padding-top: -30px;*/\n"
"    subcontrol-origin: margin;\n"
"     subcontrol-position: top center; /* position at the top center */\n"
"}")
        self.groupBox_optional.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_optional.setObjectName("groupBox_optional")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_optional)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.monthlabel = QtWidgets.QLabel(self.groupBox_optional)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.monthlabel.setFont(font)
        self.monthlabel.setStyleSheet("background-color: transparent;")
        self.monthlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.monthlabel.setObjectName("monthlabel")
        self.gridLayout_3.addWidget(self.monthlabel, 0, 1, 1, 1)
        self.day_label = QtWidgets.QLabel(self.groupBox_optional)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.day_label.setFont(font)
        self.day_label.setStyleSheet("background-color: transparent;")
        self.day_label.setAlignment(QtCore.Qt.AlignCenter)
        self.day_label.setObjectName("day_label")
        self.gridLayout_3.addWidget(self.day_label, 0, 2, 1, 1)
        self.exp_label = QtWidgets.QLabel(self.groupBox_optional)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.exp_label.setFont(font)
        self.exp_label.setObjectName("exp_label")
        self.gridLayout_3.addWidget(self.exp_label, 1, 0, 1, 1)
        self.month_combo = QtWidgets.QComboBox(self.groupBox_optional)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.month_combo.setFont(font)
        self.month_combo.setObjectName("month_combo")
        self.month_combo.addItem("")
        self.month_combo.setItemText(0, "")
        self.gridLayout_3.addWidget(self.month_combo, 1, 1, 1, 1)
        self.day_combo = QtWidgets.QComboBox(self.groupBox_optional)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.day_combo.setFont(font)
        self.day_combo.setObjectName("day_combo")
        self.day_combo.addItem("")
        self.day_combo.setItemText(0, "")
        self.gridLayout_3.addWidget(self.day_combo, 1, 2, 1, 1)
        self.year_combo = QtWidgets.QComboBox(self.groupBox_optional)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.year_combo.setFont(font)
        self.year_combo.setObjectName("year_combo")
        self.year_combo.addItem("")
        self.year_combo.setItemText(0, "")
        self.gridLayout_3.addWidget(self.year_combo, 1, 3, 1, 2)
        self.year_label = QtWidgets.QLabel(self.groupBox_optional)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.year_label.setFont(font)
        self.year_label.setStyleSheet("background-color: transparent;")
        self.year_label.setAlignment(QtCore.Qt.AlignCenter)
        self.year_label.setObjectName("year_label")
        self.gridLayout_3.addWidget(self.year_label, 0, 3, 1, 2)
        self.favorites_check = TouchCheckbox(self.groupBox_optional)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.favorites_check.setFont(font)
        self.favorites_check.setObjectName("favorites_check")
        self.gridLayout_3.addWidget(self.favorites_check, 2, 0, 1, 5, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.groupBox_optional, 1, 1, 1, 3)
        self.groupBox_main = QtWidgets.QGroupBox(NewItemDetails)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_main.sizePolicy().hasHeightForWidth())
        self.groupBox_main.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.groupBox_main.setFont(font)
        self.groupBox_main.setStyleSheet("QGroupBox\n"
"{\n"
"    margin-top: 25px;\n"
"}\n"
"\n"
"QGroupBox::title\n"
"{\n"
"    padding-top: 0px;\n"
"    margin-top: 0px;\n"
"    subcontrol-origin: margin;\n"
"     subcontrol-position: top center; /* position at the top center */\n"
"}")
        self.groupBox_main.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_main.setFlat(True)
        self.groupBox_main.setCheckable(False)
        self.groupBox_main.setObjectName("groupBox_main")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_main)
        self.gridLayout_2.setContentsMargins(5, 10, 5, 5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.itemName_label = QtWidgets.QLabel(self.groupBox_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.itemName_label.setFont(font)
        self.itemName_label.setObjectName("itemName_label")
        self.gridLayout_2.addWidget(self.itemName_label, 0, 0, 1, 1)
        self.category_label = QtWidgets.QLabel(self.groupBox_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.category_label.setFont(font)
        self.category_label.setObjectName("category_label")
        self.gridLayout_2.addWidget(self.category_label, 1, 0, 1, 3)
        self.itemQty_label = QtWidgets.QLabel(self.groupBox_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.itemQty_label.setFont(font)
        self.itemQty_label.setObjectName("itemQty_label")
        self.gridLayout_2.addWidget(self.itemQty_label, 2, 0, 1, 2)
        self.itemQty_combo = QtWidgets.QComboBox(self.groupBox_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.itemQty_combo.setFont(font)
        self.itemQty_combo.setObjectName("itemQty_combo")
        self.gridLayout_2.addWidget(self.itemQty_combo, 2, 2, 1, 2)
        self.pkgQty_label = QtWidgets.QLabel(self.groupBox_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.pkgQty_label.setFont(font)
        self.pkgQty_label.setObjectName("pkgQty_label")
        self.gridLayout_2.addWidget(self.pkgQty_label, 2, 4, 1, 1)
        self.pkgQty_combo = QtWidgets.QComboBox(self.groupBox_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.pkgQty_combo.setFont(font)
        self.pkgQty_combo.setObjectName("pkgQty_combo")
        self.gridLayout_2.addWidget(self.pkgQty_combo, 2, 5, 1, 1)
        self.itemName_textBox = TouchLineEdit(self.groupBox_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.itemName_textBox.setFont(font)
        self.itemName_textBox.setMaxLength(20)
        self.itemName_textBox.setObjectName("itemName_textBox")
        self.gridLayout_2.addWidget(self.itemName_textBox, 0, 1, 1, 5)
        self.category_combo = QtWidgets.QComboBox(self.groupBox_main)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.category_combo.setFont(font)
        self.category_combo.setObjectName("category_combo")
        self.gridLayout_2.addWidget(self.category_combo, 1, 3, 1, 3)
        self.gridLayout.addWidget(self.groupBox_main, 0, 1, 1, 3)
        self.groupBox_main.raise_()
        self.groupBox_optional.raise_()

        self.retranslateUi(NewItemDetails)
        QtCore.QMetaObject.connectSlotsByName(NewItemDetails)

    def retranslateUi(self, NewItemDetails):
        _translate = QtCore.QCoreApplication.translate
        NewItemDetails.setWindowTitle(_translate("NewItemDetails", "Dialog"))
        self.groupBox_optional.setTitle(_translate("NewItemDetails", "Optional Details"))
        self.monthlabel.setText(_translate("NewItemDetails", "Month"))
        self.day_label.setText(_translate("NewItemDetails", "Day"))
        self.exp_label.setText(_translate("NewItemDetails", "Expiration Date"))
        self.year_label.setText(_translate("NewItemDetails", "Year"))
        self.favorites_check.setText(_translate("NewItemDetails", "Add Item to Favorites"))
        self.groupBox_main.setTitle(_translate("NewItemDetails", "New Item Details"))
        self.itemName_label.setText(_translate("NewItemDetails", "Item Name"))
        self.category_label.setText(_translate("NewItemDetails", "Product Category"))
        self.itemQty_label.setText(_translate("NewItemDetails", "Item Quantity"))
        self.pkgQty_label.setText(_translate("NewItemDetails", "Qty Per Pkg"))

from Widgets.touchButton import TouchButton
from Widgets.touchCheckbox import TouchCheckbox
from Widgets.touchLineEdit import TouchLineEdit
import Resource_BY_rc
import style_rc
