# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewItemDetails.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NewItemDetails(object):
    def setupUi(self, NewItemDetails):
        NewItemDetails.setObjectName("NewItemDetails")
        NewItemDetails.resize(570, 431)
        font = QtGui.QFont()
        font.setPointSize(19)
        NewItemDetails.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(NewItemDetails)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_1.addItem(spacerItem)
        self.accept_button = TouchButton(NewItemDetails)
        self.accept_button.setMinimumSize(QtCore.QSize(45, 45))
        self.accept_button.setMaximumSize(QtCore.QSize(45, 45))
        self.accept_button.setStyleSheet("background-color: #31363B;\n"
"border: 0;")
        self.accept_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/GreenCheckIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accept_button.setIcon(icon)
        self.accept_button.setIconSize(QtCore.QSize(40, 40))
        self.accept_button.setObjectName("accept_button")
        self.horizontalLayout_1.addWidget(self.accept_button)
        self.cancel_button = TouchButton(NewItemDetails)
        self.cancel_button.setMinimumSize(QtCore.QSize(45, 45))
        self.cancel_button.setMaximumSize(QtCore.QSize(45, 45))
        self.cancel_button.setStyleSheet("background-color: #31363B;\n"
"border: 0;")
        self.cancel_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Icons/RedCancelIcon_Finished.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_button.setIcon(icon1)
        self.cancel_button.setIconSize(QtCore.QSize(40, 40))
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_1.addWidget(self.cancel_button)
        self.gridLayout.addLayout(self.horizontalLayout_1, 17, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 17, 0, 1, 1)
        self.groupBox_optional = QtWidgets.QGroupBox(NewItemDetails)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.groupBox_optional.setFont(font)
        self.groupBox_optional.setObjectName("groupBox_optional")
        self.exp_label = QtWidgets.QLabel(self.groupBox_optional)
        self.exp_label.setGeometry(QtCore.QRect(10, 90, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.exp_label.setFont(font)
        self.exp_label.setObjectName("exp_label")
        self.month_combo = QtWidgets.QComboBox(self.groupBox_optional)
        self.month_combo.setGeometry(QtCore.QRect(140, 80, 101, 50))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.month_combo.setFont(font)
        self.month_combo.setObjectName("month_combo")
        self.month_combo.addItem("")
        self.month_combo.setItemText(0, "")
        self.monthlabel = QtWidgets.QLabel(self.groupBox_optional)
        self.monthlabel.setGeometry(QtCore.QRect(150, 50, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.monthlabel.setFont(font)
        self.monthlabel.setObjectName("monthlabel")
        self.day_label = QtWidgets.QLabel(self.groupBox_optional)
        self.day_label.setGeometry(QtCore.QRect(260, 40, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.day_label.setFont(font)
        self.day_label.setObjectName("day_label")
        self.year_label = QtWidgets.QLabel(self.groupBox_optional)
        self.year_label.setGeometry(QtCore.QRect(370, 40, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.year_label.setFont(font)
        self.year_label.setObjectName("year_label")
        self.day_combo = QtWidgets.QComboBox(self.groupBox_optional)
        self.day_combo.setGeometry(QtCore.QRect(250, 80, 101, 50))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.day_combo.setFont(font)
        self.day_combo.setObjectName("day_combo")
        self.day_combo.addItem("")
        self.day_combo.setItemText(0, "")
        self.year_combo = QtWidgets.QComboBox(self.groupBox_optional)
        self.year_combo.setGeometry(QtCore.QRect(360, 80, 124, 50))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.year_combo.setFont(font)
        self.year_combo.setObjectName("year_combo")
        self.year_combo.addItem("")
        self.year_combo.setItemText(0, "")
        self.favorites_check = QtWidgets.QCheckBox(self.groupBox_optional)
        self.favorites_check.setGeometry(QtCore.QRect(180, 140, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.favorites_check.setFont(font)
        self.favorites_check.setObjectName("favorites_check")
        self.gridLayout.addWidget(self.groupBox_optional, 5, 0, 1, 3)
        self.groupBox_main = QtWidgets.QGroupBox(NewItemDetails)
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.groupBox_main.setFont(font)
        self.groupBox_main.setObjectName("groupBox_main")
        self.itemName_textBox = QtWidgets.QLineEdit(self.groupBox_main)
        self.itemName_textBox.setGeometry(QtCore.QRect(100, 40, 311, 35))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(16)
        self.itemName_textBox.setFont(font)
        self.itemName_textBox.setObjectName("itemName_textBox")
        self.itemName_label = QtWidgets.QLabel(self.groupBox_main)
        self.itemName_label.setGeometry(QtCore.QRect(10, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.itemName_label.setFont(font)
        self.itemName_label.setObjectName("itemName_label")
        self.category_label = QtWidgets.QLabel(self.groupBox_main)
        self.category_label.setGeometry(QtCore.QRect(10, 80, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.category_label.setFont(font)
        self.category_label.setObjectName("category_label")
        self.itemQty_combo = QtWidgets.QComboBox(self.groupBox_main)
        self.itemQty_combo.setGeometry(QtCore.QRect(130, 130, 81, 40))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(16)
        self.itemQty_combo.setFont(font)
        self.itemQty_combo.setObjectName("itemQty_combo")
        self.itemQty_label = QtWidgets.QLabel(self.groupBox_main)
        self.itemQty_label.setGeometry(QtCore.QRect(10, 130, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.itemQty_label.setFont(font)
        self.itemQty_label.setObjectName("itemQty_label")
        self.category_combo = QtWidgets.QComboBox(self.groupBox_main)
        self.category_combo.setGeometry(QtCore.QRect(160, 80, 254, 44))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(16)
        self.category_combo.setFont(font)
        self.category_combo.setObjectName("category_combo")
        self.category_combo.addItem("")
        self.category_combo.setItemText(0, "")
        self.pkgQty_label = QtWidgets.QLabel(self.groupBox_main)
        self.pkgQty_label.setGeometry(QtCore.QRect(240, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(19)
        self.pkgQty_label.setFont(font)
        self.pkgQty_label.setObjectName("pkgQty_label")
        self.pkgQty_combo = QtWidgets.QComboBox(self.groupBox_main)
        self.pkgQty_combo.setGeometry(QtCore.QRect(420, 130, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Cronus Round")
        font.setPointSize(16)
        self.pkgQty_combo.setFont(font)
        self.pkgQty_combo.setObjectName("pkgQty_combo")
        self.gridLayout.addWidget(self.groupBox_main, 4, 0, 1, 3)

        self.retranslateUi(NewItemDetails)
        QtCore.QMetaObject.connectSlotsByName(NewItemDetails)

    def retranslateUi(self, NewItemDetails):
        _translate = QtCore.QCoreApplication.translate
        NewItemDetails.setWindowTitle(_translate("NewItemDetails", "Dialog"))
        self.groupBox_optional.setTitle(_translate("NewItemDetails", "Optional Details"))
        self.exp_label.setText(_translate("NewItemDetails", "Expiration Date"))
        self.monthlabel.setText(_translate("NewItemDetails", "Month"))
        self.day_label.setText(_translate("NewItemDetails", "Day"))
        self.year_label.setText(_translate("NewItemDetails", "Year"))
        self.favorites_check.setText(_translate("NewItemDetails", "Add to Favorites List"))
        self.groupBox_main.setTitle(_translate("NewItemDetails", "New Item Details"))
        self.itemName_label.setText(_translate("NewItemDetails", "Item Name"))
        self.category_label.setText(_translate("NewItemDetails", "Product Category"))
        self.itemQty_label.setText(_translate("NewItemDetails", "Item Quantity"))
        self.pkgQty_label.setText(_translate("NewItemDetails", "Quantity Per Package"))

from Widgets.touchButton import TouchButton
import Resource_BY_rc
import style_rc
